dist: xenial
sudo: false

language: node_js
node_js:
  - "10"

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run-script build
  - pwd
  - cd dist/angular-github-pages-travis
  - ls
  - cd ../..
  - ls

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/angular-github-pages-travis
  on:
    branch: master
